#version: '3.2'

#services:

  #frontend:
  #  build: frontend
  #  ports:
  #    - 20080:80
  #  volumes:
  #    # Re-use local composer cache via host-volume
  #    - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
  #    - ./:/app

  #backend:
  #  build: backend
  #  ports:
  #    - 21080:80
  #  volumes:
      # Re-use local composer cache via host-volume
  #    - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #    # Mount source-code for development
  #    - ./:/app

  #mysql:
  #  image: mysql:5.7
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=verysecret
  #    - MYSQL_DATABASE=yii2advanced
  #    - MYSQL_USER=yii2advanced
  #    - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret

services:
  # PHP-FPM
  php:
    image: yiisoftware/yii2-php:8.2-apache
    build:
      context: ./docker/php
      args:
        UID: 1000
        GID: 1000
    container_name: test-php
    ports:
      - "8086:80"
    volumes:
      - .:/app
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    working_dir: /app
    networks:
      - test-network

  # Nginx
#  nginx:
#    image: nginx:stable-alpine
#    container_name: test-nginx
#    ports:
#      - "8085:80"
#    volumes:
#      - .:/app
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - test-network
#    depends_on:
#      - php

  # MySQL
  db:
    image: mysql:8.0
    container_name: test-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - test-network

  # phpMyAdmin (удобно для проверки БД)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: test-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - test-network
    depends_on:
      - db

volumes:
  db-data:

networks:
  test-network:
    driver: bridge
